Loaded dependency [python3/3.7.11]: gcc/10.3.0-binutils-2.36.1
Loaded module: python3/3.7.11

Loading python3/3.7.11
  Loading requirement: gcc/10.3.0-binutils-2.36.1
Loaded module: cuda/10.2
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.2
Loaded module: ffmpeg/4.2.2
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/fa/4/127501/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/fa/4/127501/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.3.1 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /zhome/fa/4/127501/.local/include/python3.7m/importlib-metadata
  sysconfig: /zhome/fa/4/127501/.local/include/python3.7/importlib-metadata
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/fa/4/127501/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/fa/4/127501/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.3.1 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/fa/4/127501/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/fa/4/127501/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.3.1 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
Loaded module: cuda/10.2
Loaded module: cudnn/v7.6.5.32-prod-cuda-10.2
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/fa/4/127501/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/fa/4/127501/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.3.1 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /zhome/fa/4/127501/.local/include/python3.7m/importlib-metadata
  sysconfig: /zhome/fa/4/127501/.local/include/python3.7/importlib-metadata
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/fa/4/127501/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/fa/4/127501/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.3.1 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/fa/4/127501/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/fa/4/127501/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 21.3.1 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
/zhome/fa/4/127501/.local/lib/python3.7/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    complete_policy = create_and_train_network()
  File "main.py", line 117, in create_and_train_network
    action, log_prob, value = policy.act(obs)
  File "main.py", line 66, in act
    x = x.cuda().contiguous()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
